### ISSUE TITLE
Unable to run ProxyJacker

### ISSUE THREAD

**Issue by NewbieACL** [RikunjSindhwad/ProxyJacker#1]
Hi, 

I am prompted with this error when running proxyjacker. Would anyone be kind enough to let me know what is the solution to it:

Traceback (most recent call last):
  File "proxydllhijacker.py", line 86, in <module>
    main()
  File "proxydllhijacker.py", line 70, in main
    check_arch(sys.argv[1])
  File "proxydllhijacker.py", line 43, in check_arch
    pe = pefile.PE(dllname)
  File "/home/kali/.local/lib/python2.7/site-packages/pefile.py", line 1754, in __init__
    self.__parse__(name, data, fast_load)
  File "/home/kali/.local/lib/python2.7/site-packages/pefile.py", line 1847, in __parse__
    raise PEFormatError('DOS Header magic not found.')
pefile.PEFormatError: 'DOS Header magic not found.'

**Comment by RikunjSindhwad** [comment]
You have to provide DLL file too else it won't wok, i seems you provided non binary file, make sure its windows binary. You can drop your dll here so i can check.
